services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: dyor-hub-postgres-dev
    restart: always
    env_file:
      - ../../apps/api/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5433:5432'
    networks:
      - dyor-hub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for session management
  redis:
    image: redis:7-alpine
    container_name: dyor-hub-redis-dev
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - '127.0.0.1:6380:6379'
    networks:
      - dyor-hub-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS API with hot reload
  api:
    depends_on:
      init-service:
        condition: service_completed_successfully
      types-watcher:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: node:22-alpine
    container_name: dyor-hub-api-dev
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm && 
             cd apps/api && 
             pnpm install && 
             pnpm run build && 
             pnpm run start:dev"
    volumes:
      - ../../.:/app:delegated
      - api-node-modules:/app/node_modules
      - ../../secrets:/app/secrets:ro
    env_file:
      - ../../apps/api/.env
    ports:
      - '127.0.0.1:3001:3001'
    networks:
      - dyor-hub-network

  # Types package watcher for live reloading
  types-watcher:
    image: node:22-alpine
    container_name: dyor-hub-types-watcher
    working_dir: /packages/types
    command: >
      sh -c "npm install -g pnpm && 
             pnpm install && 
             pnpm run dev"
    volumes:
      - ../../packages/types:/packages/types:delegated
      - types-node-modules:/packages/types/node_modules
    env_file:
      - ../../apps/api/.env
    networks:
      - dyor-hub-network

  # Initialization service for migrations and seeding
  init-service:
    depends_on:
      postgres:
        condition: service_healthy
    image: node:22-alpine
    container_name: dyor-hub-init-service
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm && 
             pnpm install && cd apps/api && 
             echo 'Starting database clearing...' && 
             npm run db:clear && 
             echo 'Database clearing completed. Starting database creation...' && 
             npm run db:create && 
             echo 'Database creation completed. Starting database initialization...' && 
             npm run db:init:dev &&
             echo 'Database initialization completed. Starting migrations...' && 
             npm run migration:run && 
             echo 'Migrations completed. Starting seeding...' && 
             npm run db:seed && 
             echo 'Database seeding completed.'"
    volumes:
      - ../../.:/app:delegated
      - api-node-modules:/app/node_modules
      - ../../secrets:/app/secrets
    env_file:
      - ../../apps/api/.env
    networks:
      - dyor-hub-network

  # Next.js Frontend with hot reload
  web:
    depends_on:
      init-service:
        condition: service_completed_successfully
      types-watcher:
        condition: service_started
      api:
        condition: service_started
    image: node:22-alpine
    container_name: dyor-hub-web-dev
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm && 
             cd apps/web && 
             pnpm install && 
             pnpm run dev"
    volumes:
      - ../../.:/app:delegated
      - web-node-modules:/app/node_modules
      - web-next-cache:/app/apps/web/.next
      - ../../secrets:/app/secrets:ro
    env_file:
      - ../../apps/web/.env
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - dyor-hub-network

networks:
  dyor-hub-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  api-node-modules:
  web-node-modules:
  web-next-cache:
  types-node-modules:
